/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMeineKundenIndexRouteImport } from './routes/_authenticated/meine-kunden/index'
import { Route as ApiPublicAuthConfigRouteImport } from './routes/api/public/auth-config'
import { Route as AuthenticatedMeineKundenSystemhouseIdCustomerIdRouteImport } from './routes/_authenticated/meine-kunden/$systemhouseId.$customerId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeineKundenIndexRoute =
  AuthenticatedMeineKundenIndexRouteImport.update({
    id: '/meine-kunden/',
    path: '/meine-kunden/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAuthConfigRoute = ApiPublicAuthConfigRouteImport.update({
  id: '/api/public/auth-config',
  path: '/api/public/auth-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeineKundenSystemhouseIdCustomerIdRoute =
  AuthenticatedMeineKundenSystemhouseIdCustomerIdRouteImport.update({
    id: '/meine-kunden/$systemhouseId/$customerId',
    path: '/meine-kunden/$systemhouseId/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/public/auth-config': typeof ApiPublicAuthConfigRoute
  '/meine-kunden/': typeof AuthenticatedMeineKundenIndexRoute
  '/meine-kunden/$systemhouseId/$customerId': typeof AuthenticatedMeineKundenSystemhouseIdCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/public/auth-config': typeof ApiPublicAuthConfigRoute
  '/meine-kunden': typeof AuthenticatedMeineKundenIndexRoute
  '/meine-kunden/$systemhouseId/$customerId': typeof AuthenticatedMeineKundenSystemhouseIdCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/public/auth-config': typeof ApiPublicAuthConfigRoute
  '/_authenticated/meine-kunden/': typeof AuthenticatedMeineKundenIndexRoute
  '/_authenticated/meine-kunden/$systemhouseId/$customerId': typeof AuthenticatedMeineKundenSystemhouseIdCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/api/status'
    | '/api/sync'
    | '/api/public/auth-config'
    | '/meine-kunden/'
    | '/meine-kunden/$systemhouseId/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/api/status'
    | '/api/sync'
    | '/api/public/auth-config'
    | '/meine-kunden'
    | '/meine-kunden/$systemhouseId/$customerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/api/status'
    | '/api/sync'
    | '/api/public/auth-config'
    | '/_authenticated/meine-kunden/'
    | '/_authenticated/meine-kunden/$systemhouseId/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiPublicAuthConfigRoute: typeof ApiPublicAuthConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meine-kunden/': {
      id: '/_authenticated/meine-kunden/'
      path: '/meine-kunden'
      fullPath: '/meine-kunden/'
      preLoaderRoute: typeof AuthenticatedMeineKundenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/auth-config': {
      id: '/api/public/auth-config'
      path: '/api/public/auth-config'
      fullPath: '/api/public/auth-config'
      preLoaderRoute: typeof ApiPublicAuthConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meine-kunden/$systemhouseId/$customerId': {
      id: '/_authenticated/meine-kunden/$systemhouseId/$customerId'
      path: '/meine-kunden/$systemhouseId/$customerId'
      fullPath: '/meine-kunden/$systemhouseId/$customerId'
      preLoaderRoute: typeof AuthenticatedMeineKundenSystemhouseIdCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeineKundenIndexRoute: typeof AuthenticatedMeineKundenIndexRoute
  AuthenticatedMeineKundenSystemhouseIdCustomerIdRoute: typeof AuthenticatedMeineKundenSystemhouseIdCustomerIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeineKundenIndexRoute: AuthenticatedMeineKundenIndexRoute,
  AuthenticatedMeineKundenSystemhouseIdCustomerIdRoute:
    AuthenticatedMeineKundenSystemhouseIdCustomerIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiPublicAuthConfigRoute: ApiPublicAuthConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
